kind: pipeline
type: exec
name: default

platform:
  os: windows

steps:
- name: compile
  commands:
  - %comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
  - msbuild

