kind: pipeline
type: exec
name: default

platform:
  os: windows

steps:
- name: compile
  environment:
    msbuild_path:
      from_secret: msbuild_path
  commands:
  - C:\Program Files '(x86')\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
