kind: pipeline
type: exec
name: default

platform:
  os: windows

steps:
- name: build
  commands:
  - Invoke-MsBuild -Path DontDisableMyEthernet.sln -ShowBuildOutputInCurrentWindow -PassThru
- name: create compressed package
  commands:
    - Compress-Archive -Path DontDisableMyEthernetService\bin\Debug\*.* -DestinationPath DontDisableMyEthernetService.zip
- name: upload artifacts
  environment:
    access_key:
      from_secret: access_key
    secret_key:
      from_secret: secret_key
  commands:
    - Write-S3Object -AccessKey $env:access_key -SecretKey $env:secret_key -BucketName artifacts -File DontDisableMyEthernetService.zip -EndpointUrl https://s3.decryptology.net/artifacts/DontDisableMyEthernetService